env:
  global:
  - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct;
    else git log -1 --skip 1 --pretty=format:%ct; fi)
language: ruby
cache: bundler
rvm:
- 2.3
- 2.4
- jruby-9.1.5.0
- jruby-9.1.9.0
jdk:
- oraclejdk8
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
script:
- bundle exec rake
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
deploy:
  provider: rubygems
  on:
    tags: true
    rvm: 2.3
  api_key:
    secure: AutAtC9BtCfKjnvOAnULGqtpwVfZ1N5GvF86g92BBpGj/mzZRuLvrRiGL7BjfclSLPJAIxeCvapWzj3HTdB7D4755uwXTDDOZQpVD4a8MXRO6IWDNzGV0whZIIHTjh6X68oEXIHC4lKTeMiSfJS21FqJNoIGZlRxtGcgxcMVMi3JAHidjeh32ZOh6TroWRfY+1aOt4lWzgwIzMuRFV9qX1uK+vmOrwYKejPck0ETwPMJqKDiHlxRlDYOq5JF2I2eTu+AaMj3I6R+EbqnsiaDgT451//TcSfcaIoHErWjSuYRwXGIeqzugxRuh7MNpY7FeTipjO//7h1du2rEcR2gJyYH9IPzpYjmAoAmz/dQTPPqIh5mAE4C+RWsuyYQNOiXMEI+mXz6IdA6u0cJLXKYf2CV/oMDCu2KFM1OWNzAsnarTwIiIs6DnD6ID34qvVwfRBLqVZMYJtbooaMPBS8DlQorMLFIfpVHwHdRfDnSpSsAOHICayXm3ErhI33bnhR+QUjwn6PGsaTOPKKQtK5Wp3wLIiJTBkSnAwR0wZCj5q/+GIaEKArmtEFTrzKkFrU2BhM6iERHKV0uCARZMCnZG8cfuJVMklbwGQyPbZ2pqKXTeSQn1IPzxUrpclW2loFK/MgX5QhZcxSvtZ62xultEIX2OFdMVfBH73mdgNCQusQ=
